# Generated by Django 5.0.14 on 2026-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('PRODUCER', 'Producteur'), ('ADMIN', 'Admin'), ('PRESS_CRITIC', 'Critique de presse')], default='USER', max_length=20),
        ),
    ]
