# Generated by Django 5.0.14 on 2025-11-18 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="description",
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
