# Generated by Django 5.0.14 on 2025-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_price_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locality", models.CharField(max_length=60)),
                ("postcode", models.CharField(max_length=6)),
            ],
            options={
                "db_table": "localities",
            },
        ),
    ]
