# Generated by Django 5.0.14 on 2025-11-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_locality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locality",
            old_name="postcode",
            new_name="postal_code",
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=60, unique=True)),
                ("designation", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                (
                    "locality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="locations",
                        to="catalogue.locality",
                    ),
                ),
            ],
            options={
                "db_table": "locations",
            },
        ),
    ]
