# Generated by Django 5.0.14 on 2025-11-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_reservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=60, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255, null=True)),
                ("poster_url", models.CharField(max_length=255, null=True)),
                ("duration", models.PositiveSmallIntegerField(null=True)),
                ("created_in", models.DateField(auto_now_add=True)),
                ("bookable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "shows",
            },
        ),
        migrations.AlterField(
            model_name="locality",
            name="locality",
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name="locality",
            constraint=models.UniqueConstraint(
                fields=("postal_code", "locality"), name="unique_postal_code_locality"
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shows",
                to="catalogue.location",
            ),
        ),
    ]
