# Generated by Django 5.0.14 on 2025-11-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_alter_show_created_in_location_unique_slug_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Representation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="representations",
                        to="catalogue.location",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="representations",
                        to="catalogue.show",
                    ),
                ),
            ],
            options={
                "db_table": "representations",
            },
        ),
    ]
