# Generated by Django 5.0.14 on 2025-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_representation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="show",
            constraint=models.UniqueConstraint(
                fields=("slug", "created_in"), name="unique_slug_created_in"
            ),
        ),
    ]
