# Generated by Django 5.0.14 on 2025-11-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="types",
            field=models.ManyToManyField(
                db_table="artist_type", related_name="artists", to="catalogue.type"
            ),
        ),
    ]
