# Generated by Django 5.0.14 on 2025-11-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_artist_unique_firstname_lastname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artist",
            name="unique_firstname_lastname",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="types",
        ),
    ]
