# Generated by Django 5.0.14 on 2025-12-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0020_artist_unique_firstname_lastname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artist",
            name="unique_firstname_lastname",
        ),
    ]
