# Generated by Django 5.0.14 on 2026-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_reservation_quantity_reservation_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='available_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
