# Generated by Django 5.0.14 on 2026-04-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_merge_20260415_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='catalogue.artist'),
        ),
        migrations.AddField(
            model_name='show',
            name='publication_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='representation',
            name='available_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
