# Generated by Django 5.0.14 on 2026-04-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalogue.show')),
            ],
            options={
                'db_table': 'show_prices',
                'ordering': ['amount'],
            },
        ),
    ]
