# Generated by Django 5.0.14 on 2026-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0031_add_show_price_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='spoken_language',
            field=models.CharField(choices=[('fr', 'Français'), ('nl', 'Nederlands'), ('en', 'English')], default='fr', max_length=10),
        ),
    ]
