# Generated by Django 5.0.14 on 2026-05-11 00:00

from decimal import Decimal
from django.db import migrations, models


def backfill_total_paid(apps, schema_editor):
    Reservation = apps.get_model('catalogue', 'Reservation')

    for reservation in Reservation.objects.prefetch_related('representation_reservations__price').all():
        if reservation.total_paid and reservation.total_paid > Decimal('0.00'):
            continue

        total_paid = Decimal('0.00')
        if reservation.payment_status == 'paid':
            for line in reservation.representation_reservations.all():
                if line.price_id and line.price_id:
                    total_paid += line.price.price * line.quantity

        if total_paid > Decimal('0.00'):
            reservation.total_paid = total_paid
            reservation.save(update_fields=['total_paid'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_alter_review_show_alter_review_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_total_paid, migrations.RunPython.noop),
    ]