# Generated by Django 5.0.14 on 2026-05-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.locality'),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
