# Generated by Django 5.0.14 on 2025-11-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_remove_artist_unique_firstname_lastname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="a_artistTypes",
                        to="catalogue.artist",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="t_artistTypes",
                        to="catalogue.type",
                    ),
                ),
            ],
            options={
                "db_table": "artist_type",
            },
        ),
    ]
