# Generated by Django 5.0.14 on 2025-11-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_artisttypeshow"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="artist_types",
            field=models.ManyToManyField(
                related_name="shows",
                through="catalogue.ArtistTypeShow",
                to="catalogue.artisttype",
            ),
        ),
    ]
