# Generated by Django 5.0.14 on 2025-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_show_artist_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.UniqueConstraint(
                fields=("firstname", "lastname"), name="unique_firstname_lastname"
            ),
        ),
    ]
