# Generated by Django 5.0.14 on 2026-04-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_artist_firstname_en_artist_firstname_fr_and_more'),
        ('catalogue', '0024_reservation_payment_status'),
    ]

    operations = [
    ]
