# Generated by Django 5.0.14 on 2025-10-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bookable', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.location')),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='catalog.show')),
            ],
        ),
    ]
