# Generated by Django 5.0.14 on 2025-10-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='location',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.location'),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
